# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 253c0b938a82f63520210207d7589342f7d4996498a625c344519deab83c31fd4aa2dc17b06b586b8d032a21cbbc7273424a245456a18ba4a49a05d9b0fe221e

test:
  secret_key_base: cc204006cf813bfd5ff8e4e27cdf6f4853955b22e15f274162e6cd912ee917454b64e86e744a26653dd3d1b440b6519b36d997c97760436c1bbc3e8a3bf1de4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
